import React from "react";
import { motion } from "motion/react";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function PrivacyPolicy() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-black text-neutral-300 py-20 px-6">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl mx-auto"
      >
        <button 
          onClick={() => navigate("/")}
          className="flex items-center gap-2 text-amber-500 font-bold mb-12 hover:text-amber-400 transition-colors"
        >
          <ArrowLeft className="w-5 h-5 flex-shrink-0" />
          العودة للمتجر
        </button>

        <div className="prose prose-invert prose-amber max-w-none">
          <h1 className="text-4xl font-black text-white mb-8 tracking-tight">Privacy Policy</h1>  
          <p className="text-neutral-500 mb-8">Last updated: May 08, 2026</p>  
          
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>  
          <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>  
          
          <h2 className="text-2xl font-bold text-white mt-12 mb-4">Interpretation and Definitions</h2>  
          <h3 className="text-xl font-bold text-white mt-8 mb-4">Interpretation</h3>  
          <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>  
          
          <h3 className="text-xl font-bold text-white mt-8 mb-4">Definitions</h3>  
          <p>For the purposes of this Privacy Policy:</p>  
          <ul className="list-disc pl-6 space-y-2">  
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>  
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>  
            <li><strong>Application</strong> refers to سكانور, the software program provided by the Company.</li>  
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to سكانور.</li>  
            <li><strong>Country</strong> refers to: Saudi Arabia</li>  
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>  
            <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</li>  
            <li><strong>Service</strong> refers to the Application.</li>  
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>  
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>  
            <li><strong>You</strong> means the individual accessing or using the Service.</li>  
          </ul>  

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">Collecting and Using Your Personal Data</h2>  
          <h3 className="text-xl font-bold text-white mt-8 mb-4">Types of Data Collected</h3>  
          <h4 className="text-lg font-bold text-white mt-6 mb-2">Personal Data</h4>  
          <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>  
          <ul className="list-disc pl-6 space-y-2">  
            <li>Email address</li>  
            <li>First name and last name</li>  
            <li>Phone number</li>  
          </ul>  

          <h4 className="text-lg font-bold text-white mt-6 mb-2">Usage Data</h4>  
          <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>  

          <h3 className="text-xl font-bold text-white mt-8 mb-4">Use of Your Personal Data</h3>  
          <p>The Company may use Personal Data for the following purposes:</p>  
          <ul className="list-disc pl-6 space-y-2">  
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>  
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>  
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract.</li>  
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>  
            <li><strong>To provide You</strong> with news, special offers, and general information about other goods.</li>  
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>  
          </ul>  

          <h3 className="text-xl font-bold text-white mt-8 mb-4">Retention of Your Personal Data</h3>  
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations.</p>  

          <h3 className="text-xl font-bold text-white mt-8 mb-4">Transfer of Your Personal Data</h3>  
          <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction.</p>  

          <h3 className="text-xl font-bold text-white mt-8 mb-4">Security of Your Personal Data</h3>  
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>  

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">Children's Privacy</h2>  
          <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>  

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">Changes to this Privacy Policy</h2>  
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>  

          <h2 className="text-2xl font-bold text-white mt-12 mb-4">Contact Us</h2>  
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>  
          <ul className="list-disc pl-6 space-y-2">  
            <li>By phone: 00966552232752</li>  
          </ul>  
        </div>
      </motion.div>
    </div>
  );
}
